### PR TITLE
Allow multiple lines of text in buttons

### LINKED ISSUE #55: Line height is too big
See screenshot

seat_moves__uk_parliament_seat_projection

### PR DESCRIPTION
**Pull request by kaelig**
Fixes #55 

screenshot 2015-03-20 13 09 37

### CODE REVIEW

**Comment by kavanagh** [comment]
Code nice. Visually leading is ok with me too. Do you need a double-deck example with an icon?

**Comment by kaelig** [comment]
Cheers.

Not sure multi line + icon makes sense, see for yourself:

screenshot 2015-03-20 14 06 14

**Comment by kaelig** [comment]
Also added a test for input type = submit :

screenshot 2015-03-20 14 16 49

**Comment by kavanagh** [comment]
Re Icons. I meant the vertical alignment shouldn't look weird. Unlikely case but a product might need to do it. What you have is good/tidy.

**Comment by kaelig** [comment]
Right. Seems like an edge case, let's not worry too much about it.

**Pull request merged**
